<a href="https://colab.research.google.com/github/lovelyzhu/aaa/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install finlab

Collecting finlab
  Downloading finlab-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 25.2 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from finlab) (2.27.1)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.10/dist-packages (from finlab) (1.22.4)
Requirement already satisfied: pandas>=1.5.3 in /usr/local/lib/python3.10/dist-packages (from finlab) (1.5.3)
Requirement already satisfied: pyarrow>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from finlab) (9.0.0)
Collecting lz4 (from finlab)
  Downloading lz4-4.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 46.3 MB/s eta 0:00:00
Requirement already satisfied: Cython in /usr/local/lib/python3.10/dist-packages (from finlab) (0.29.36)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from finlab) (4.65.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from finlab) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.3->finlab) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.3->finlab) (2022.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->finlab) (2.1.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->finlab) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->finlab) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->finlab) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->finlab) (3.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.5.3->finlab) (1.16.0)
Installing collected packages: lz4, finlab
Successfully installed finlab-0.4.5 lz4-4.3.2

In [2]:
from finlab import data

In [3]:
df=data.get('price:收盤價')

輸入成功!

WARNING:finlab.data:Due to your status as a free user,the most recent data has been shortened or limited.
WARNING:finlab.data:price:收盤價 -- Daily usage: 12.2 / 500 MB

In [4]:
df.head()

symbol,0015,0050,0051,0052,0053,0054,0055,0056,0057,0058,...,9944,9945,9946,9949,9950,9951,9955,9958,9960,9962
date,,,,,,,,,,,,,,,,,,,,,
2013-01-02,7.64,54.40,26.09,32.72,23.26,19.40,11.47,22.95,31.94,32.12,...,16.55,62.7,19.05,20.5,19.2,42.3,29.10,13.50,17.25,12.70
2013-01-03,7.64,54.85,26.12,32.12,23.11,19.37,11.49,23.06,31.93,31.96,...,16.60,67.0,18.95,20.2,19.2,42.2,29.25,13.35,17.30,12.85
2013-01-04,7.64,54.50,26.00,32.48,22.97,19.40,11.38,22.95,31.87,32.30,...,16.55,66.1,19.10,20.3,19.4,41.6,29.25,13.15,17.30,13.00
2013-01-07,7.64,54.25,25.84,32.09,22.81,19.21,11.39,22.97,NaN,31.94,...,17.20,65.6,19.50,20.0,19.5,41.7,29.40,13.45,17.20,12.85
2013-01-08,7.60,53.90,25.68,31.72,22.72,19.01,11.36,22.80,31.61,31.90,...,17.50,64.5,19.25,19.8,19.3,41.7,28.95,13.25,17.10,12.80